### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

### The Basics

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
# Get shape
print("Get Shape :- ",a.shape)

# Get Type
print("Get Typy :- ",a.dtype)

# Get Size
print("Get Size :- ",a.itemsize)

Get Shape :-  (3,)
Get Typy :-  int32
Get Size :-  4


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
print("Get Dimension :- ",b.ndim)

# Get total size
print("Get Total Size :- ",b.nbytes)

# Get number of elements
print("Get number of elements :- ",b.size)

Get Dimension :-  2
Get Total Size :-  48
Get number of elements :-  6


### Accessing/Changing specific elements, rows, columns, etc

In [6]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
# Get a specific element [row, column]
print("Get a specific element :- ", a[1, 5])

# Get a specific row 
print("Get a specific row  :- ", a[0, :]) # 0 = row, : = all collumn

# Get a specific column
print("Get a specific column :-", a[:, 2]) # : all row, 2 = collimn

Get a specific element :-  13
Get a specific row  :-  [1 2 3 4 5 6 7]
Get a specific column :- [ 3 10]


In [8]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2] # 0 = start row, 1:-1 = value one to last, :2 = step

array([2, 4, 6])

In [9]:
a[1,5] = 20
print(a)
a[:,2] = [1,2] # Here change [3,10] to [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [10]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
# Get specific element (work outside in)
b[1,0,1] # 1 = Dim, 0 = Row, 1 = Column

6

In [12]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [13]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [14]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [15]:
# b[:,1,:] = [[9,9,],[8,8]] = This is wrong

### Initializing Different Types of Arrays

In [16]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [18]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [19]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [20]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.81050135, 0.32577266],
       [0.80228709, 0.71065932],
       [0.47805601, 0.02574369],
       [0.92190733, 0.27134097]])

In [21]:
# Random Integer values
np.random.randint(-4,8, size=(3,3)) # -4 to 8 size 3 = row, 3 = collumn

array([[ 5,  6, -3],
       [ 6, -3,  1],
       [-1, -3,  1]])

In [22]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [24]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [25]:
a = np.array([1,2,3])
b = a.copy()
b[1] = 100

print(a)
print(b)

[1 2 3]
[  1 100   3]


### Mathematics

In [26]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [27]:
a + 2

array([3, 4, 5, 6])

In [28]:
a - 2

array([-1,  0,  1,  2])

In [29]:
a * 2

array([2, 4, 6, 8])

In [30]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [31]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [32]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [33]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [34]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [35]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [36]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [37]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [38]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.min(stats)

1

In [40]:
np.max(stats, axis=1)

array([3, 6])

In [41]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [54]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [51]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [48]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [49]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])